import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { base44 } from '@/api/base44Client';
import { Calculator, Save, Star, Download } from 'lucide-react';
import { calculatePlanetaryPositions, calculateAscendant } from '../components/utils/AstrologicalCalculations';

export default function BirthChartCalculator() {
  const [formData, setFormData] = useState({
    name: '',
    birth_date: '',
    birth_time: '',
    birth_latitude: '',
    birth_longitude: '',
    birth_place: ''
  });
  const [calculatedChart, setCalculatedChart] = useState(null);
  const [calculating, setCalculating] = useState(false);

  const handleCalculate = async () => {
    setCalculating(true);

    const birthDateTime = new Date(`${formData.birth_date}T${formData.birth_time}`);
    const lat = parseFloat(formData.birth_latitude);
    const lon = parseFloat(formData.birth_longitude);

    // Calculate planetary positions
    const planetaryPositions = calculatePlanetaryPositions(lat, lon, birthDateTime);
    
    // Calculate ascendant
    const ascendant = calculateAscendant(lat, lon, birthDateTime);

    // Find moon sign and sun sign
    const moonPosition = planetaryPositions.find(p => p.name === 'Moon');
    const sunPosition = planetaryPositions.find(p => p.name === 'Sun');

    const zodiacSigns = [
      'Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo',
      'Libra', 'Scorpio', 'Sagittarius', 'Capricorn', 'Aquarius', 'Pisces'
    ];

    const moonSign = zodiacSigns[Math.floor(moonPosition.longitude / 30)];
    const sunSign = zodiacSigns[Math.floor(sunPosition.longitude / 30)];

    const chart = {
      ascendant_sign: ascendant.sign,
      moon_sign: moonSign,
      sun_sign: sunSign,
      nakshatra: moonPosition.nakshatra,
      planetary_positions: planetaryPositions,
      chart_data: {
        ascendant,
        birthDateTime: birthDateTime.toISOString()
      }
    };

    setCalculatedChart(chart);
    setCalculating(false);
  };

  const handleSave = async () => {
    if (!calculatedChart) {
      alert('Please calculate the birth chart first');
      return;
    }

    try {
      await base44.entities.BirthChart.create({
        name: formData.name,
        birth_date: new Date(`${formData.birth_date}T${formData.birth_time}`).toISOString(),
        birth_latitude: parseFloat(formData.birth_latitude),
        birth_longitude: parseFloat(formData.birth_longitude),
        birth_place: formData.birth_place,
        ascendant_sign: calculatedChart.ascendant_sign,
        moon_sign: calculatedChart.moon_sign,
        sun_sign: calculatedChart.sun_sign,
        nakshatra: calculatedChart.nakshatra,
        planetary_positions: calculatedChart.planetary_positions,
        chart_data: calculatedChart.chart_data
      });

      alert('✨ Birth chart saved successfully!');
    } catch (error) {
      console.error('Error saving birth chart:', error);
      alert('❌ Failed to save birth chart. Please try again.');
    }
  };

  const handleDownload = () => {
    if (!calculatedChart) return;

    const chartText = `
VEDIC BIRTH CHART (JANAM KUNDALI)
Generated on ${new Date().toLocaleDateString()}

Name: ${formData.name}
Birth Date: ${formData.birth_date} ${formData.birth_time}
Birth Place: ${formData.birth_place}
Coordinates: ${formData.birth_latitude}°, ${formData.birth_longitude}°

MAIN POSITIONS:
- Ascendant (Lagna): ${calculatedChart.ascendant_sign}
- Moon Sign (Rashi): ${calculatedChart.moon_sign}
- Sun Sign: ${calculatedChart.sun_sign}
- Nakshatra: ${calculatedChart.nakshatra}

PLANETARY POSITIONS:
${calculatedChart.planetary_positions.map(p => 
  `${p.name} (${p.sanskrit}): ${Math.floor(p.longitude)}° - ${p.nakshatra}`
).join('\n')}

Generated by Astro Finder - Universal Astrometry Engine
    `.trim();

    const blob = new Blob([chartText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `birth-chart-${formData.name.replace(/\s+/g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen p-4 md:p-8" style={{ background: '#0a0612' }}>
      <div className="max-w-6xl mx-auto">
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-white mb-2 bg-gradient-to-r from-yellow-400 to-orange-400 bg-clip-text text-transparent">
            Vedic Birth Chart Calculator
          </h1>
          <p className="text-blue-200">Janam Kundali / Horoscope Generation</p>
        </div>

        <div className="grid lg:grid-cols-2 gap-6">
          <Card className="bg-black/40 backdrop-blur-xl border-white/20 shadow-2xl">
            <CardHeader>
              <CardTitle className="text-white flex items-center gap-2">
                <Calculator className="w-5 h-5 text-yellow-400" />
                Birth Details
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="name" className="text-white">Full Name</Label>
                <Input
                  id="name"
                  value={formData.name}
                  onChange={(e) => setFormData({...formData, name: e.target.value})}
                  placeholder="Enter full name"
                  className="bg-white/10 border-white/20 text-white"
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="birth_date" className="text-white">Birth Date</Label>
                  <Input
                    id="birth_date"
                    type="date"
                    value={formData.birth_date}
                    onChange={(e) => setFormData({...formData, birth_date: e.target.value})}
                    className="bg-white/10 border-white/20 text-white"
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="birth_time" className="text-white">Birth Time</Label>
                  <Input
                    id="birth_time"
                    type="time"
                    value={formData.birth_time}
                    onChange={(e) => setFormData({...formData, birth_time: e.target.value})}
                    className="bg-white/10 border-white/20 text-white"
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="birth_place" className="text-white">Birth Place</Label>
                <Input
                  id="birth_place"
                  value={formData.birth_place}
                  onChange={(e) => setFormData({...formData, birth_place: e.target.value})}
                  placeholder="City, Country"
                  className="bg-white/10 border-white/20 text-white"
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="latitude" className="text-white">Latitude</Label>
                  <Input
                    id="latitude"
                    type="number"
                    step="0.0001"
                    value={formData.birth_latitude}
                    onChange={(e) => setFormData({...formData, birth_latitude: e.target.value})}
                    placeholder="28.6139"
                    className="bg-white/10 border-white/20 text-white"
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="longitude" className="text-white">Longitude</Label>
                  <Input
                    id="longitude"
                    type="number"
                    step="0.0001"
                    value={formData.birth_longitude}
                    onChange={(e) => setFormData({...formData, birth_longitude: e.target.value})}
                    placeholder="77.2090"
                    className="bg-white/10 border-white/20 text-white"
                  />
                </div>
              </div>

              <Button
                onClick={handleCalculate}
                disabled={calculating || !formData.name || !formData.birth_date || !formData.birth_time}
                className="w-full bg-gradient-to-r from-yellow-600 to-orange-600 hover:from-yellow-700 hover:to-orange-700"
              >
                <Star className="w-4 h-4 mr-2" />
                {calculating ? 'Calculating...' : 'Generate Birth Chart'}
              </Button>
            </CardContent>
          </Card>

          {calculatedChart && (
            <Card className="bg-gradient-to-br from-purple-900/40 to-pink-900/30 backdrop-blur-xl border-purple-500/30 shadow-2xl">
              <CardHeader>
                <CardTitle className="text-white">Your Birth Chart (Kundali)</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div className="bg-white/10 rounded-lg p-4">
                    <p className="text-sm text-purple-300 mb-1">Ascendant (Lagna)</p>
                    <p className="text-2xl font-bold text-white">{calculatedChart.ascendant_sign}</p>
                  </div>

                  <div className="bg-white/10 rounded-lg p-4">
                    <p className="text-sm text-purple-300 mb-1">Moon Sign (Rashi)</p>
                    <p className="text-2xl font-bold text-white">{calculatedChart.moon_sign}</p>
                  </div>

                  <div className="bg-white/10 rounded-lg p-4">
                    <p className="text-sm text-purple-300 mb-1">Sun Sign</p>
                    <p className="text-2xl font-bold text-white">{calculatedChart.sun_sign}</p>
                  </div>

                  <div className="bg-white/10 rounded-lg p-4">
                    <p className="text-sm text-purple-300 mb-1">Nakshatra</p>
                    <p className="text-xl font-bold text-white">{calculatedChart.nakshatra}</p>
                  </div>
                </div>

                <div className="bg-white/5 rounded-lg p-4">
                  <p className="text-sm text-purple-300 mb-3">Planetary Positions</p>
                  <div className="space-y-2 text-sm">
                    {calculatedChart.planetary_positions.map((planet) => (
                      <div key={planet.name} className="flex justify-between items-center">
                        <span className="text-white">{planet.name} ({planet.sanskrit})</span>
                        <span className="text-purple-200">
                          {Math.floor(planet.longitude)}° {planet.nakshatra}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <Button
                    onClick={handleSave}
                    className="bg-gradient-to-r from-green-600 to-teal-600 hover:from-green-700 hover:to-teal-700"
                  >
                    <Save className="w-4 h-4 mr-2" />
                    Save
                  </Button>
                  <Button
                    onClick={handleDownload}
                    variant="outline"
                    className="border"
                    style={{ 
                      borderColor: 'rgba(141, 124, 238, 0.5)',
                      color: '#fffff4',
                      backgroundColor: 'rgba(141, 124, 238, 0.1)'
                    }}
                  >
                    <Download className="w-4 h-4 mr-2" />
                    Download
                  </Button>
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
}